//-----AUTH-----

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

//-----USERS-----

export const FETCH_SINGLE_USER_REQUEST = 'FETCH_SINGLE_USER_REQUEST'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_FAIL = 'FETCH_SINGLE_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'

//-----ROOMS-----

export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL'

export const FETCH_SINGLE_ROOM_REQUEST = 'FETCH_SINGLE_ROOM_REQUEST'
export const FETCH_SINGLE_ROOM_SUCCESS = 'FETCH_SINGLE_ROOM_SUCCESS'
export const FETCH_SINGLE_ROOM_FAIL = 'FETCH_SINGLE_ROOM_FAIL'

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST'
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL'

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST"
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
export const DELETE_ROOM_FAIL = "DELETE_ROOM_FAIL"

export const FETCH_ROOMS_REQUEST = 'FETCH_ROOMS_REQUEST'
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS'
export const FETCH_ROOMS_FAIL = 'FETCH_ROOMS_FAIL'

export const ROOM_AVAILABILITY_REQUEST = 'ROOM_AVAILABILITY_REQUEST'
export const ROOM_AVAILABILITY_SUCCESS = 'ROOM_AVAILABILITY_SUCCESS'
export const ROOM_AVAILABILITY_FAIL = 'ROOM_AVAILABILITY_FAIL'

//-----HOTELS-----

export const CREATE_HOTEL_REQUEST = 'CREATE_HOTEL_REQUEST'
export const CREATE_HOTEL_SUCCESS = 'CREATE_HOTEL_SUCCESS'
export const CREATE_HOTEL_FAIL = 'CREATE_HOTEL_FAIL'

export const FETCH_SINGLE_HOTEL_REQUEST = 'FETCH_SINGLE_HOTEL_REQUEST'
export const FETCH_SINGLE_HOTEL_SUCCESS = 'FETCH_SINGLE_HOTEL_SUCCESS'
export const FETCH_SINGLE_HOTEL_FAIL = 'FETCH_SINGLE_HOTEL_FAIL'

export const UPDATE_HOTEL_REQUEST = 'UPDATE_HOTEL_REQUEST'
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS'
export const UPDATE_HOTEL_FAIL = 'UPDATE_HOTEL_FAIL'

export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST"
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS"
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL"

export const FETCH_HOTELS_REQUEST = 'FETCH_HOTELS_REQUEST'
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS'
export const FETCH_HOTELS_FAIL = 'FETCH_HOTELS_FAIL'

export const FETCH_HOTELS_BY_CITY_REQUEST = 'FETCH_HOTELS_BY_CITY_REQUEST'
export const FETCH_HOTELS_BY_CITY_SUCCESS = 'FETCH_HOTELS_BY_CITY_SUCCESS'
export const FETCH_HOTELS_BY_CITY_FAIL = 'FETCH_HOTELS_BY_CITY_FAIL'

export const COUNT_HOTELS_BY_TYPE_REQUEST = 'COUNT_HOTELS_BY_TYPE_REQUEST'
export const COUNT_HOTELS_BY_TYPE_SUCCESS = 'COUNT_HOTELS_BY_TYPE_SUCCESS'
export const COUNT_HOTELS_BY_TYPE_FAIL = 'COUNT_HOTELS_BY_TYPE_FAIL'

export const FEATURED_PROP_REQUEST = 'FEATURED_PROP_REQUEST'
export const FEATURED_PROP_SUCCESS = 'FEATURED_PROP_SUCCESS'
export const FEATURED_PROP_FAIL = 'FEATURED_PROP_FAIL'

export const SEARCH_HOTEL_REQUEST = 'SEARCH_HOTEL_REQUEST'
export const SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS'
export const SEARCH_HOTEL_FAIL = 'SEARCH_HOTEL_FAIL'

export const FETCH_HOTEL_ROOMS_REQUEST = 'FETCH_HOTEL_ROOMS_REQUEST'
export const FETCH_HOTEL_ROOMS_SUCCESS = 'FETCH_HOTEL_ROOMS_SUCCESS'
export const FETCH_HOTEL_ROOMS_FAIL = 'FETCH_HOTEL_ROOMS_FAIL'

//-----RESERVATION-----

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_FAIL = 'CREATE_RESERVATION_FAIL'

export const FETCH_SINGLE_RESERVATION_REQUEST = 'FETCH_SINGLE_RESERVATION_REQUEST'
export const FETCH_SINGLE_RESERVATION_SUCCESS = 'FETCH_SINGLE_RESERVATION_SUCCESS'
export const FETCH_SINGLE_RESERVATION_FAIL = 'FETCH_SINGLE_RESERVATION_FAIL'

export const FETCH_RESERVATIONS_REQUEST = 'FETCH_RESERVATIONS_REQUEST'
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS'
export const FETCH_RESERVATIONS_FAIL = 'FETCH_RESERVATIONS_FAIL'

export const FETCH_MY_RESERVATIONS_REQUEST = 'FETCH_MY_RESERVATIONS_REQUEST'
export const FETCH_MY_RESERVATIONS_SUCCESS = 'FETCH_MY_RESERVATIONS_SUCCESS'
export const FETCH_MY_RESERVATIONS_FAIL = 'FETCH_MY_RESERVATIONS_FAIL'
